version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout

      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-

      - run:
          name: Install dependencies
          command: npm i

      - run:
          name: Run tests
          command: npm test

      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  logic-proxy:
    jobs:
      - build
