version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout

      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-dev-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-node-dev-{{ arch }}-{{ .Branch }}-
            - v1-node-dev-{{ arch }}-

      - run:
          name: Install dependencies
          command: npm i

      - run:
          name: Run tests
          command: npm test

      - save_cache:
          name: Save node_modules cache
          key: v1-node-dev-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout

      - run:
          name: Install awscli, jq and zip
          command: |
            sudo apt update
            sudo apt install -y jq zip python3-pip
            pip3 install awscli --upgrade

      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-prod-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-node-prod-{{ arch }}-{{ .Branch }}-
            - v1-node-prod-{{ arch }}-

      - run:
          name: Install production dependencies only
          command: npm i --only=prod

      - save_cache:
          name: Save node_modules cache
          key: v1-node-prod-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: Zip the sources of the lambda
          command: |
            zip -r bt-to-orion.zip data src node_modules package.json index.js

      - store_artifacts:
          path: bt-to-orion.zip

workflows:
  version: 2
  logic-proxy:
    jobs:
      - test
      - build:
          requires:
            - test
